### PR TITLE
Make kind local registry optional

### LINKED ISSUE #393: kn quickstart kind error exit status 1
```bash
kn quickstart kind
```
```bash
Running Knative Quickstart using Kind
Error: creating cluster: failed to delete local registry: exit status 1
Usage:
  kn-quickstart kind [flags]

Flags:
  -h, --help                        help for kind
      --install-eventing            install Eventing on quickstart cluster
      --install-serving             install Serving on quickstart cluster
  -k, --kubernetes-version string   kubernetes version to use (1.x.y) or (kindest/node:v1.x.y)
  -n, --name string                 kind cluster name to be used by kn-quickstart (default "knative")

creating cluster: failed to delete local registry: exit status 1
Error: exit status 1
```

### PR DESCRIPTION
**Pull request by psschwei**
# Changes

Fixes #393 

Installing a local registry causes problems for podman users. This PR makes the local registry opt-in by passing a `--registry` flag.

Also bumps the Kubernetes version to v1.26.6.

**Release Note**

```release-note
For Kind, a local registry will no longer be created by default. Users will need to pass the `--registry` flag if they wish to create a local registry.
```

### CODE REVIEW

File: internal/command/flags.go [hunk 1]
```diff
@@ -51,3 +52,7 @@ func installServingOption(targetCmd *cobra.Command) {
 func installEventingOption(targetCmd *cobra.Command) {
 	targetCmd.Flags().BoolVar(&installEventing, "install-eventing", false, "install Eventing on quickstart cluster")
 }
+
+func installKindRegistryOption(targetCmd *cobra.Command) {
+	targetCmd.Flags().BoolVar(&installKindRegistry, "registry", false, "install registry for kind quickstart cluster")
```
Comment (dsimansk) [inline internal/command/flags.go:57]: Maybe start with cap `Kind`?
```suggestion
	targetCmd.Flags().BoolVar(&installKindRegistry, "registry", false, "install registry for Kind quickstart cluster")
```
